### ISSUE TITLE
可以兼容Nightingale 3.3.0吗？

### ISSUE THREAD

**Issue by FCCloud** [seaframework/sea-monitor-all#1]
目前上报数据的链接是2.x版本的，是否可以直接修改为/api/transfer/push，就可以上报数据到3.3.0

**Comment by spyvip** [comment]
@FCCloud  根据官方文档，只是API地址进行变更，请求数据结构未变化，因此是支持的

`https://github.com/didi/nightingale/wiki/API_05_%E7%9B%91%E6%8E%A7%E6%95%B0%E6%8D%AE`
